In [15]:
%load_ext autoreload
%autoreload 2
from trade.datamanager import (
    DividendDataManager,
    SpotDataManager,
    OptionSpotDataManager,
    VolDataManager,
    RatesDataManager,
    BaseDataManager,
    ForwardDataManager,
    GreekDataManager,
    assert_synchronized_model,
    get_option_theoretical_price,
    calculate_scenarios,
)

from trade.datamanager._enums import (
    OptionSpotEndpointSource,
    SeriesId,
    OptionPricingModel,
    VolatilityModel,
    RealTimeFallbackOption,
    GreekType,
    ModelPrice,
)
from trade.optionlib.config.types import DivType
from trade.helpers.helper_types import SingletonMetaClass
from trade.datamanager.vars import get_loaded_names, TS
from trade.datamanager.utils.model import LoadRequest, _load_model_data_timeseries
from trade.datamanager.utils.logging import (
    change_datamanager_factor_loggers_level,
    change_datamanager_utils_logging_level,
    change_logging_in_all_datamanager_loggers,
    change_all_optionlib_loggers_level,
)

# change_datamanager_factor_loggers_level("CRITICAL")
# change_datamanager_utils_logging_level("CRITICAL")
# change_logging_in_all_datamanager_loggers("CRITICAL")
change_all_optionlib_loggers_level("CRITICAL")
get_loaded_names()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
2026-02-02 14:22:53 trade.helpers.Logging INFO: Logging Root Directory: /Users/chiemelienwanisobi/cloned_repos/QuantTools/logs
2026-02-02 14:22:53 [test] trade.helpers.clear_cache INFO: No expired caches to delete on 2026-02-02.
2026-02-02 14:22:57 [test] dbase.DataAPI.ThetaData.proxy INFO: Refreshed proxy URL: http://54.205.248.219:5500/thetadata
2026-02-02 14:22:57 [test] dbase.DataAPI.ThetaData.proxy INFO: Using Proxy URL: http://54.205.248.219:5500/thetadata
2026-02-02 14:22:57 [test] dbase.DataAPI.ThetaData INFO: Using V2 of the ThetaData API


Scheduled Data Requests will be saved to: /Users/chiemelienwanisobi/cloned_repos/QuantTools/module_test/raw_code/DataManagers/scheduler/requests.jsonl
2026-02-02 14:23:00 [test] DataManager.py CRITICAL: Using ProcessSaveManager for saving data.
Fetching rates data from yfinance directly during market hours

set()

In [16]:
## Vars
div = DivType.CONTINUOUS
undo_adjust = True
endpoint_source = OptionSpotEndpointSource.EOD
series_id = SeriesId.HIST
market_model = OptionPricingModel.BSM
vol_model = VolatilityModel.MARKET
model_price = ModelPrice.ASK

symbol = "SBUX"
expiration = "2026-09-18"
right = "C"
strike = 100.0
ts_start = "2025-01-01"
ts_end = "2026-01-28"

In [17]:
request = LoadRequest(
    symbol=symbol,
    # start_date=ts_start,
    # end_date=ts_end,
    as_of=ts_end,
    expiration=expiration,
    strike=strike,
    right=right,
    series_id=SeriesId.HIST,
    dividend_type=DivType.DISCRETE,
    endpoint_source=OptionSpotEndpointSource.EOD,
    vol_model=VolatilityModel.MARKET,
    market_model=OptionPricingModel.BINOMIAL,
    model_price=ModelPrice.ASK,
    load_spot=True,
    load_dividend=True,
    load_forward=True,
    load_option_spot=True,
    load_vol=True,
    load_greek=True,
    load_rates=True,
    undo_adjust=True,
    # rt=True,
)
data_packet = _load_model_data_timeseries(request)

2026-02-02 14:23:04 [test] trade.datamanager.vars INFO: Loading timeseries for SBUX...
2026-02-02 14:23:07 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:07 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 14:23:07 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 14:23:08 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 14:23:08 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-28 to 2026-01-28...
2026-02-02 14:23:08 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:08 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 14:23:08 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:08 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:08 [test] trade.datamanager.forward INFO: Cache hit for forward timeseries key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-28 to 2026-01-28...
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Using cached date range for 2026-01-28 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C100
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:100
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-28 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 14:23:08 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:SBUX|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:100
2026-02-02 14:23:08 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 14:23:08 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Using cached date range for 2026-01-28 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C100
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-28 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Cache hit for vol timeseries key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Using cached date range for 2026-01-28 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C100
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-28 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 14:23:08 [test] trade.datamanager.utils INFO: Cache hit for greeks timeseries key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market

In [18]:
data_packet.greek.fallback_option

In [19]:
request.end_date

Timestamp('2026-01-28 00:00:00')

In [20]:
bsm = calculate_scenarios(
    symbol=symbol,
    expiration=expiration,
    right=right,
    strike=strike,
    return_pnl_in_pct=True,
    return_pnl=True,
    rt=True
)

2026-02-02 14:23:09 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:09 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:09 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:09 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 14:23:09 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 14:23:09 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 14:23:09 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 14:23:11 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D to avoid saving partial day data.
2026-02-02 14:23:11 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 14:23:11 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:12 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol SBUX.
2026-02-02 14:23:14 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 14:23:15 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 14:23:15 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-02-02 14:23:15 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick SBUX20260918C100
2026-02-02 14:23:15 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 14:23:15 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates.
2026-02-02 14:23:15 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().

Exception ignored on calling ctypes callback function: <function ExecutionEngine._raw_object_cache_notify at 0x11aa47a60>
Traceback (most recent call last):
  File "/Users/chiemelienwanisobi/miniconda3/envs/openbb_new_use/lib/python3.11/site-packages/llvmlite/binding/executionengine.py", line 178, in _raw_object_cache_notify
    def _raw_object_cache_notify(self, data):

KeyboardInterrupt:

2026-02-02 14:23:18 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market to avoid saving partial day data.
2026-02-02 14:23:18 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...

In [ ]:
RatesDataManager().rt().timeseries

2026-02-02 11:44:46 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:46 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:44:48 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:44:48 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:44:46.443119. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:44:48 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:48 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:48 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:44:48 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:44:46 for 2026-02-02 as fallback.

datetime
2026-02-02    0.03575
Name: annualized, dtype: float64

In [22]:
SpotDataManager("SBUX").rt().timeseries

2026-02-02 14:23:37 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 14:23:37 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol SBUX.
2026-02-02 14:23:39 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...

2026-02-02    91.860001
Name: close, dtype: object

In [29]:
import yfinance as yf
yf.download(
    tickers="SBUX",
    start="2026-01-01",
    # end="2024-06-01",
    end="2026-02-03",
    interval="1d",
)

[*********************100%***********************]  1 of 1 completed

Price           Close        High        Low        Open    Volume
Ticker           SBUX        SBUX       SBUX        SBUX      SBUX
Date
2026-01-02  83.970001   84.959999  83.019997   84.220001  11334900
2026-01-05  86.559998   87.250000  83.400002   83.500000   9894300
2026-01-06  89.459999   90.639999  86.360001   86.559998  11351100
2026-01-07  86.690002   89.379997  86.470001   89.019997   9547000
2026-01-08  88.180000   89.290001  85.610001   85.860001   8140100
2026-01-09  88.879997   89.099998  86.790001   88.349998   7593200
2026-01-12  89.959999   90.230003  87.599998   88.400002   7289500
2026-01-13  90.559998   90.599998  89.470001   89.690002   5561900
2026-01-14  91.150002   91.519997  90.150002   90.260002   8373200
2026-01-15  93.279999   94.169998  91.639999   92.070000  10001700
2026-01-16  92.989998   93.669998  92.220001   93.360001   8958200
2026-01-20  93.660004   93.809998  90.779999   91.760002  13555200
2026-01-21  96.430000   96.519997  93.730003   93.820000  17118100
2026-01-22  95.830002   97.800003  94.860001   96.470001  14150800
2026-01-23  97.620003   97.889999  95.760002   97.099998  11759800
2026-01-26  96.330002   97.970001  95.790001   97.209999  14106700
2026-01-27  95.720001   96.650002  95.239998   95.769997  16403600
2026-01-28  95.160004  104.820000  95.099998  102.300003  25961600
2026-01-29  93.879997   96.900002  92.610001   96.760002  16602900
2026-01-30  91.949997   93.209999  91.000000   92.720001  10744300
2026-02-02  91.864998   92.610001  90.629997   91.839996   5419473

In [55]:
t = yf.Ticker("AAPL").history(
    start="2025-02-01",
    end="2026-02-03",
    interval="1d",
    # progress=False,
    # multi_level_index=False,
)
t.index = t.index.tz_localize(None)
t

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-02-03,228.954495,230.786206,224.683801,226.983398,73063300,0.0,0.0
2025-02-04,226.226817,232.080347,225.629512,231.751831,45067300,0.0,0.0
2025-02-05,227.501062,231.622421,227.242238,231.423325,39620300,0.0,0.0
2025-02-06,230.248634,232.747343,229.392506,232.169952,29925300,0.0,0.0
2025-02-07,231.552758,232.946448,226.236789,226.605133,39707200,0.0,0.0
...,...,...,...,...,...,...,...
2026-01-27,259.170013,261.950012,258.209991,258.269989,49648300,0.0,0.0
2026-01-28,257.649994,258.859985,254.509995,256.440002,41288000,0.0,0.0
2026-01-29,258.000000,259.649994,254.410004,258.279999,67253000,0.0,0.0
2026-01-30,255.169998,261.899994,252.179993,259.480011,92352600,0.0,0.0
2026-02-02,260.019989,270.489990,259.204987,270.010010,72890096,0.0,0.0

In [ ]:
yf.Ticker("AAPL").pr

In [57]:
RatesDataManager()._query_yfinance(
    start_date="2026-02-02",
    end_date="2026-02-02",
    interval="1d",
)

            name            description     daily  annualized
Datetime
2026-02-02  ^IRX  13 WEEK TREASURY BILL  0.000096     0.03578

In [ ]:
bsm.grid

           0.90      0.95      1.00      1.05      1.10
-0.02 -0.602754 -0.382721 -0.097780  0.255275  0.676231
-0.01 -0.566061 -0.339467 -0.048809  0.308528  0.731857
 0.00 -0.529591 -0.296411  0.000006  0.361682  0.787452
 0.01 -0.493324 -0.253536  0.048678  0.414746  0.843016
 0.02 -0.457242 -0.210827  0.097217  0.467723  0.898549

## Batch Load Real Time

In [ ]:
option_metas = [
    {
        "symbol": "SBUX",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 100.0,
    },
    {
        "symbol": "SBUX",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 105.0,
    },
    {
        "symbol": "AAPL",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 260.0,
    },
    {
        "symbol": "AAPL",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 265.0,
    },
    {
        "symbol": "AMD",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 280.0,
    },
    {
        "symbol": "AMD",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 290.0,
    },
    {
        "symbol": "META",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 890.0,
    },
    {
        "symbol": "META",
        "expiration": "2026-09-18",
        "right": "C",
        "strike": 900.0,
    }
]

In [ ]:
full_data = []
for option_meta in option_metas:
    option_scenarios = calculate_scenarios(
        symbol=option_meta["symbol"],
        expiration=option_meta["expiration"],
        right=option_meta["right"],
        strike=option_meta["strike"],
        return_pnl_in_pct=True,
        return_pnl=True,
        rt=True
    )
    full_data.append(option_scenarios)

2026-02-02 11:44:48 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:48 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:48 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:48 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE

2026-02-02 11:44:48 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:44:48 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:48 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:44:50 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:44:50 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:44:48.761262. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:44:50 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:50 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:50 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:44:50 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:44:48 for 2026-02-02 as fallback.
2026-02-02 11:44:50 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:50 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol SBUX.
2026-02-02 11:44:52 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:44:52 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:44:52 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-02-02 11:44:52 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick SBUX20260918C100
2026-02-02 11:44:52 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:44:52 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates.
2026-02-02 11:44:52 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:44:52 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market to avoid saving partial day data.
2026-02-02 11:44:52 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:44:52 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:52 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:52 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:52 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:44:52 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:44:52 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:52 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:44:54 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:44:54 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:44:52.925818. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:44:54 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:54 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:44:54 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:44:54 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:44:52 for 2026-02-02 as fallback.
2026-02-02 11:44:54 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:44:54 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol SBUX.
2026-02-02 11:44:56 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:44:56 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:44:56 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-02-02 11:44:56 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick SBUX20260918C105
2026-02-02 11:44:56 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:44:56 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market. Fetching missing dates.
2026-02-02 11:44:56 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:44:56 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market to avoid saving partial day data.
2026-02-02 11:44:56 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:44:56 [test] trade.datamanager.vars INFO: Loading timeseries for AAPL...
2026-02-02 11:44:58 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:44:58 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:44:58 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:AAPL|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:44:58 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:45:00 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:00 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:01 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:45:01 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:45:00.206707. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:45:01 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:01 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:01 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:45:01 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:45:00 for 2026-02-02 as fallback.
2026-02-02 11:45:01 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:02 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:02 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:02 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-02-02 11:45:02 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick AAPL20260918C260
2026-02-02 11:45:02 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:02 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:02 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:02 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:02 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:02 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:02 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:02 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:02 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:AAPL|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:45:02 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:45:02 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:02 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:04 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:45:04 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:45:02.623254. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:45:04 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:04 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:04 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:45:04 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:45:02 for 2026-02-02 as fallback.
2026-02-02 11:45:04 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:04 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol AAPL.
2026-02-02 11:45:06 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:06 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:06 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-02-02 11:45:06 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick AAPL20260918C265
2026-02-02 11:45:06 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:265|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:06 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:265|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:06 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:06 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:265|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:06 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:06 [test] trade.datamanager.vars INFO: Loading timeseries for AMD...
2026-02-02 11:45:08 [test] EventDriven.riskmanager.market_data ERROR: Failed to retrieve dividends for symbol AMD
2026-02-02 11:45:08 [test] trade.datamanager.vars INFO: Timeseries for AMD already loaded.
2026-02-02 11:45:08 [test] trade.datamanager.vars INFO: Timeseries for AMD already loaded.
2026-02-02 11:45:08 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:AMD|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:45:08 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:AMD|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:45:09 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:09 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:15 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:45:15 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:45:09.018505. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:45:15 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:15 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:15 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:45:15 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:45:09 for 2026-02-02 as fallback.
2026-02-02 11:45:15 [test] trade.datamanager.vars INFO: Timeseries for AMD already loaded.
2026-02-02 11:45:15 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:15 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:15 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-02-02 11:45:15 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick AMD20260918C280
2026-02-02 11:45:15 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:AMD|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:280|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]

In [ ]:
timeseries_full_data = []
for option_meta in option_metas:
    request = LoadRequest(
        symbol=option_meta["symbol"],
        start_date=ts_start,
        end_date=ts_end,
        expiration=option_meta["expiration"],
        strike=option_meta["strike"],
        right=option_meta["right"],
        series_id=SeriesId.HIST,
        dividend_type=DivType.DISCRETE,
        endpoint_source=OptionSpotEndpointSource.EOD,
        vol_model=VolatilityModel.MARKET,
        market_model=OptionPricingModel.BINOMIAL,
        model_price=ModelPrice.ASK,
        load_spot=True,
        load_dividend=True,
        load_forward=True,
        load_option_spot=True,
        load_vol=True,
        load_greek=True,
        load_rates=True,
        undo_adjust=True,
        # rt=True,
    )
    data_packet = _load_model_data_timeseries(request)
    timeseries_full_data.append(data_packet)

2026-02-02 11:45:27 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Using provided dividend_type: DivType.DISCRETE
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Fetching discrete dividend schedule timeseries for SBUX from 2025-01-01 00:00:00 to 2026-01-28 00:00:00 with maturity 2026-09-18 00:00:00
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Cache hit for discrete schedule timeseries key: symbol:SBUX|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Cache fully covers requested date range for timeseries. Key: symbol:SBUX|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:27 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:27 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:27 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:27 [test] EventDriven.riskmanager.market_data WARNING: End date 2026-01-28 00:00:00 is in the past or current time is after market close. Preload check will be skipped if specified.
2026-02-02 11:45:27 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:27 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:27 [test] trade.datamanager.forward INFO: Cache hit for forward timeseries key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C100
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:100
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-23 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:27 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:SBUX|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:100
2026-02-02 11:45:27 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:27 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C100
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-23 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Cache hit for vol timeseries key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C100
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-23 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Cache hit for greeks timeseries key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market
2026-02-02 11:45:27 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Using provided dividend_type: DivType.DISCRETE
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Fetching discrete dividend schedule timeseries for SBUX from 2025-01-01 00:00:00 to 2026-01-28 00:00:00 with maturity 2026-09-18 00:00:00
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Cache hit for discrete schedule timeseries key: symbol:SBUX|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:27 [test] trade.datamanager.dividend INFO: Cache fully covers requested date range for timeseries. Key: symbol:SBUX|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:27 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:27 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:27 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:27 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:27 [test] EventDriven.riskmanager.market_data WARNING: End date 2026-01-28 00:00:00 is in the past or current time is after market close. Preload check will be skipped if specified.
2026-02-02 11:45:27 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:28 [test] trade.datamanager.forward INFO: Cache hit for forward timeseries key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C105
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:105
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-23 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:SBUX|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:105
2026-02-02 11:45:28 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:28 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C105
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-23 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for vol timeseries key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick SBUX20260918C105
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-23 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for greeks timeseries key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Using provided dividend_type: DivType.DISCRETE
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Fetching discrete dividend schedule timeseries for AAPL from 2025-01-01 00:00:00 to 2026-01-28 00:00:00 with maturity 2026-09-18 00:00:00
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Cache hit for discrete schedule timeseries key: symbol:AAPL|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Cache fully covers requested date range for timeseries. Key: symbol:AAPL|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:28 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:28 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:28 [test] EventDriven.riskmanager.market_data WARNING: End date 2026-01-28 00:00:00 is in the past or current time is after market close. Preload check will be skipped if specified.
2026-02-02 11:45:28 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:28 [test] trade.datamanager.forward INFO: Cache hit for forward timeseries key: symbol:AAPL|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick AAPL20260918C260
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:260
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-06 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:260
2026-02-02 11:45:28 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:28 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick AAPL20260918C260
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-06 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for vol timeseries key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick AAPL20260918C260
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-06 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Cache hit for greeks timeseries key: symbol:AAPL|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Using provided dividend_type: DivType.DISCRETE
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Fetching discrete dividend schedule timeseries for AAPL from 2025-01-01 00:00:00 to 2026-01-28 00:00:00 with maturity 2026-09-18 00:00:00
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Cache hit for discrete schedule timeseries key: symbol:AAPL|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:28 [test] trade.datamanager.dividend INFO: Cache fully covers requested date range for timeseries. Key: symbol:AAPL|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2026-09-18|method:CONSTANT|undo_adjust:1
2026-02-02 11:45:28 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:28 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:28 [test] EventDriven.riskmanager.market_data WARNING: End date 2026-01-28 00:00:00 is in the past or current time is after market close. Preload check will be skipped if specified.
2026-02-02 11:45:28 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:28 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:28 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:29 [test] trade.datamanager.forward INFO: Cache hit for forward timeseries key: symbol:AAPL|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-01-01 to 2026-01-28...
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick AAPL20260918C265
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:265
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-06 00:00:00 to 2026-01-28 00:00:00...
2026-02-02 11:45:29 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20260918T000000|right:C|strike:265
2026-02-02 11:45:29 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:29 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Using cached date range for 2025-01-01 00:00:00 - 2026-01-28 00:00:00 and option tick AAPL20260918C265
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:265|volatility_model:market
2026-02-02 11:45:29 [test] trade.datamanager.utils INFO: Sanitizing data from 2025-05-06 00:00:00 to 2026-01-28 00:00:00...

In [ ]:
timeseries_full_data

[ModelResultPack(symbol='SBUX', strike=100.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='SBUX', strike=105.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='AAPL', strike=260.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='AAPL', strike=265.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='AMD', strike=280.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='AMD', strike=290.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='META', strike=890.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0),
 ModelResultPack(symbol='META', strike=900.0, expiration=datetime.datetime(2026, 9, 18, 0, 0), right='C', series_id=<SeriesId.HIST: 'hist'>, dividend_type=<DivType.DISCRETE: 'discrete'>, undo_adjust=True, num_empty=0)]

In [ ]:
rt_full_data = []
for option_meta in option_metas:
    request = LoadRequest(
        symbol=option_meta["symbol"],

        expiration=option_meta["expiration"],
        strike=option_meta["strike"],
        right=option_meta["right"],
        series_id=SeriesId.HIST,
        dividend_type=DivType.DISCRETE,
        endpoint_source=OptionSpotEndpointSource.EOD,
        vol_model=VolatilityModel.MARKET,
        market_model=OptionPricingModel.BINOMIAL,
        model_price=ModelPrice.ASK,
        load_spot=True,
        load_dividend=True,
        load_forward=True,
        load_option_spot=True,
        load_vol=True,
        load_greek=True,
        load_rates=True,
        undo_adjust=True,
        rt=True,
    )
    data_packet = _load_model_data_timeseries(request)
    rt_full_data.append(data_packet)

2026-02-02 11:45:31 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:31 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:31 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:31 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:45:31 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:45:31 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:31 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:37 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:45:37 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:45:31.085799. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:45:37 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:37 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:37 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:45:37 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:45:31 for 2026-02-02 as fallback.
2026-02-02 11:45:37 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:37 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol SBUX.
2026-02-02 11:45:39 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:39 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:39 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:39 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:39 [test] trade.datamanager.forward INFO: Cache partially covers requested date range for forward timeseries. Key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1 to avoid saving partial day data.
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:39 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:39 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick SBUX20260918C100
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:39 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 11:45:39.743402 - 2026-02-02 11:45:39.743402 and option tick SBUX20260918C100
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:39 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:39 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:40 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:100|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:40 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:40 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:40 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:40 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:40 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:45:40 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:45:40 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:40 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:42 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:45:42 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:45:40.298922. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:45:42 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:42 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:42 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:45:42 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:45:40 for 2026-02-02 as fallback.
2026-02-02 11:45:42 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:42 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol SBUX.
2026-02-02 11:45:44 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:44 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:44 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:44 [test] trade.datamanager.vars INFO: Timeseries for SBUX already loaded.
2026-02-02 11:45:44 [test] trade.datamanager.forward INFO: Cache partially covers requested date range for forward timeseries. Key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1 to avoid saving partial day data.
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:44 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:44 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick SBUX20260918C105
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:44 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 11:45:44.651546 - 2026-02-02 11:45:44.651546 and option tick SBUX20260918C105
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:44 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:SBUX|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:105|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:44 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:44 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:44 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:44 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:44 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:AAPL|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-02-02 11:45:44 [test] trade.datamanager.dividend INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE. Fetching missing data.
2026-02-02 11:45:44 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:44 [test] trade.datamanager.rates INFO: Cache partially covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:46 [test] trade.datamanager.rates WARNING: No risk-free rate data found for date range 2026-02-02 00:00:00 to 2026-02-02 00:00:00.
2026-02-02 11:45:46 [test] trade.datamanager.rates WARNING: No rate data found for date 2026-02-02 11:45:44.715522. Resorting to fallback option `RealTimeFallbackOption.USE_LAST_AVAILABLE`.
2026-02-02 11:45:46 [test] trade.datamanager.rates INFO: Cache hit for risk-free rate timeseries key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:46 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-02-02 11:45:46 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-01-30 to 2026-01-30...
2026-02-02 11:45:46 [test] trade.datamanager.rates WARNING: Using last available rate for date 2026-01-30 11:45:44 for 2026-02-02 as fallback.
2026-02-02 11:45:46 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:46 [test] EventDriven.riskmanager.market_data CRITICAL: Reloading timeseries data for symbol AAPL.
2026-02-02 11:45:48 [test] EventDriven.riskmanager.market_data INFO: Sanitizing today's data from all stored timeseries data...
2026-02-02 11:45:48 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:48 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:48 [test] trade.datamanager.vars INFO: Timeseries for AAPL already loaded.
2026-02-02 11:45:48 [test] trade.datamanager.forward INFO: Cache partially covers requested date range for forward timeseries. Key: symbol:AAPL|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:AAPL|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2026-09-18|use_chain_spot:1 to avoid saving partial day data.
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:48 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-02-02 11:45:48 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.ASK
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 00:00:00 - 2026-02-02 00:00:00 and option tick AAPL20260918C260
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:48 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Cutting off today's data for key: symbol:AAPL|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|n_steps:100|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market to avoid saving partial day data.
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Sanitizing data from 2026-02-02 to 2026-02-02...
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Using cached date range for 2026-02-02 11:45:48.549351 - 2026-02-02 11:45:48.549351 and option tick AAPL20260918C260
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:AAPL|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market. Fetching missing dates: [Timestamp('2026-02-02 00:00:00')]
2026-02-02 11:45:48 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:AAPL|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:quote|expiration:20260918T000000|model_price:ask|option_pricing_model:Binomial|right:C|strike:260|volatility_model:market. Fetching missing dates.
2026-02-02 11:45:48 [test] trade.datamanager.utils WARNING: No data requested to load in _load_model_data_timeseries().

In [ ]:
rt_full_data[0].option_spot.price

datetime
2026-02-02    5.625
Name: midpoint, dtype: float64

In [ ]:
OptionSpotDataManager("SBUX").rt(
    strike=100.0,
    right="C",
    expiration="2026-09-18",
).price

datetime
2026-02-02    5.625
Name: midpoint, dtype: float64

In [ ]:
from dbase.database.db_utils import set_environment_context
set_environment_context("long_bbands")
from algo.positions.loaders.position_vars import get_position_data

2026-02-02 11:46:10 [long_bbands] algo.__init__ CRITICAL: ALGO_DIR not on main branch; skipping runtime safeguards.
[get_engine] Creating engine for DB: master_config (base: master_config), PID: 8931
[get_engine] Creating engine for DB: portfolio_data_long_bbands (base: portfolio_data), PID: 8931

In [ ]:
pos = get_position_data(force=True)

2026-02-02 11:46:17 [long_bbands] algo.positions.loaders.position_vars INFO: Loading position data for today: 2026-02-02
2026-02-02 11:46:17 [test] DataManager.py CRITICAL: Skipping MySQL query. This is not optimized and may lead to performance issues.
2026-02-02 11:46:17 [long_bbands] algo.positions.loaders.position_vars INFO: Loading position data (force=True, refresh=True, eod_block=False, is_today=False, date=2026-02-02)
[get_engine] Creating engine for DB: portfolio_config_long_bbands (base: portfolio_config), PID: 8931
2026-02-02 11:46:21 [long_bbands] algo.strategies._config_utils INFO: No configuration differences found for slug 'long_bbands'.
2026-02-02 11:46:21 [long_bbands] algo.strategies._config_utils INFO: No configuration differences found for slug 'long_bbands'.
2026-02-02 11:46:22 [long_bbands] algo.strategies._config_utils INFO: No configuration differences found for slug 'long_bbands'.
Fetching rates data from yfinance directly during market hours
Fetching rates data from yfinance directly during market hours
2026-02-02 11:46:33 [test] trade.asset.Stock ERROR: Error getting dividends history for AMD from yfinance
2026-02-02 11:46:33 [test] trade.asset.Stock ERROR: Probably due to no dividends history
Fetching rates data from yfinance directly during market hours
Fetching rates data from yfinance directly during market hours
2026-02-02 11:46:37 [test] trade.asset.Stock ERROR: Error setting close for BA:
[Error] -> Unauthorized FMP request -> Legacy Endpoint : Due to Legacy endpoints being no longer supported - This endpoint is only available for legacy users who have valid subscriptions prior August 31, 2025. Please visit our documentation page https://site.financialmodelingprep.com/developer/docs for our current APIs.
2026-02-02 11:46:37 [test] trade.asset.Stock ERROR:
set_variables raised an error
Traceback (most recent call last):
  File "/Users/chiemelienwanisobi/cloned_repos/QuantTools/trade/helpers/decorators.py", line 394, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chiemelienwanisobi/cloned_repos/QuantTools/trade/assets/Stock.py", line 134, in set_variables
    raise e  ## Raise error so that decorator can catch it
    ^^^^^^^
  File "/Users/chiemelienwanisobi/cloned_repos/QuantTools/trade/assets/Stock.py", line 130, in set_variables
    self.prev_close()
  File "/Users/chiemelienwanisobi/cloned_repos/QuantTools/trade/assets/Stock.py", line 440, in prev_close
    obb.equity.price.quote(symbol=self.ticker, provider="fmp").to_dataframe()["prev_close"].values[0]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chiemelienwanisobi/miniconda3/envs/openbb_new_use/lib/python3.11/site-packages/openbb_core/app/static/utils/decorators.py", line 93, in wrapper
    raise UnauthorizedError(f"\n[Error] -> {e}").with_traceback(
  File "/Users/chiemelienwanisobi/miniconda3/envs/openbb_new_use/lib/python3.11/site-packages/openbb_fmp/utils/helpers.py", line 24, in response_callback
    raise UnauthorizedError(f"Unauthorized FMP request -> {error_message}")
openbb_core.provider.utils.errors.UnauthorizedError:
[Error] -> Unauthorized FMP request -> Legacy Endpoint : Due to Legacy endpoints being no longer supported - This endpoint is only available for legacy users who have valid subscriptions prior August 31, 2025. Please visit our documentation page https://site.financialmodelingprep.com/developer/docs for our current APIs.
Fetching rates data from yfinance directly during market hours
Fetching rates data from yfinance directly during market hours
2026-02-02 11:46:50 [long_bbands] algo.positions.loaders.position_vars INFO: Using cached position data (last loaded at 2026-02-02 11:46:50.737208-05:00)

In [ ]:
pos.strategies["long_bbands"].positions[2].position_data.greeks

OptionGreeks(bs_delta=0.0, bs_gamma=0.0, bs_theta=0.01783721107952374, bs_vega=0.0, bs_rho=-0.01517916777565631, bs_volga=nan, binomial_delta=0.0, binomial_gamma=0.0, binomial_theta=0.01783721107952374, binomial_vega=0.0, binomial_rho=-0.01517916777565631, dollar_bs_delta=np.float64(0.0), dollar_binomial_delta=np.float64(0.0))